apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: kpmg-test
spec:
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: bitnami/apache:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 3
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 1
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
          ports:
          - containerPort: 8080
            name: http
          env:
            - name: TOMCAT_HOST
              value: 'tomcat'
            - name: TOMCAT_PORT
              value: '8080'
            
          resources:
            limits:
              cpu: 200m
              memory: 300Mi
            requests:
              cpu: 200m
              memory: 300Mi
     