apiVersion: v1
kind: Service
metadata:
  name: tomcat
  namespace: kpmg-test
  labels:
    app: tomcat
spec:
  type: clusterIP
  ports:
    - port: 8080
  selector:
    app: tomcat
    tier: application